<a href="https://colab.research.google.com/github/AycaCicek/Turkcell-MakineOgrenmesi/blob/main/ElasticNet_Regresyon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge,Lasso,ElasticNet
from sklearn.metrics import mean_squared_error,r2_score
from sklearn import model_selection
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import RidgeCV,LassoCV,ElasticNetCV

In [2]:
data=pd.read_csv("/content/Hitters.csv")
data.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
0    29      14      A        E      446       33      20     NaN         A  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N

In [3]:
data=data.dropna()
data_encoding=pd.get_dummies(data[["League","Division","NewLeague"]])

y = data["Salary"]#BAGIMLI DEGISKEN
##BAGIMSIZ DEGISKEN SECIMI##
X_=data.drop(["Salary","League","Division","NewLeague"],axis=1).astype("float64")
X=pd.concat([X_,data_encoding[["League_N","Division_W","NewLeague_N"]]],axis=1)
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [4]:
enet_model=ElasticNet().fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive


In [5]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [6]:
enet_model.intercept_

-6.465955602112331

In [8]:
#tahmin ve model
enet_model.predict(X_train)[0:5]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566])

In [11]:
y_pred=enet_model.predict(X_test)

In [12]:
np.sqrt(mean_squared_error(y_test,y_pred))

357.1676548181246

In [13]:
r2_score(y_test,y_pred)

0.41070222469326867

Model Tuning

In [16]:
enet_cv_model=ElasticNetCV(cv=10).fit(X_train,y_train)#max iterasyon

In [17]:
enet_cv_model.intercept_

-38.5194055839429

In [18]:
enet_cv_model.coef_

array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [19]:
enet_cv_model.alpha_

5230.7647364798695

In [20]:
#final model

In [22]:
enet_model_tuned=ElasticNet(alpha=enet_cv_model.alpha_).fit(X_train,y_train)

In [23]:
y_pred=enet_model_tuned.predict(X_test)

In [24]:
np.sqrt(mean_squared_error(y_test,y_pred))

394.15280563218795

In [25]:
?ElasticNet